# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bc946fa2ae09b6761393ac950ee9aa54bcd58ae6d7315fea6d9f084a9353133bcae0a7e3af9993c15911b51a472606d678267edea1537289c1c082522903aa5

test:
  secret_key_base: 63a4312c2bcc1150b7259ff2ba0500a5feeeebe326d4a36969aba501101c356484dce7ee3f5d99b83a89195943d4797ece892771bfcf0b877f4307e9a0b2729f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
